name: manubot-ai-editor-evals
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - langchain=0.1.*
  - nodejs=20.8.*
  - pip
  - python=3.12.*
  - pre-commit=3.5.*
  - pip:
      - langchain-openai
      - langchain-anthropic
      - jinja2==3.1.*
      - python-dotenv==1.0.*
