name: manubot-ai-editor-evals
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - nodejs=20.8.*
  - pip
  - python=3.12.*
  - pre-commit=3.5.*
  - pip:
      - openai
      - jinja2==3.1.*
      - python-dotenv==1.0.*
