name: manubot-ai-editor-evals
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - langchain=0.0.340
  - nodejs=20.8.*
  - python=3.12.*
  - pre-commit=3.5.*
  - pip:
      - openai
      - jinja2==3.1.*
