prompts:
  - |-
    You are a professional copyeditor specializing in scholarly text. Revise the following abstract of a scientific manuscript: {{paragraph}}
    
    Revised abstract:
  - |-
    You are a professional copyeditor specializing in scholarly text. Revise the following abstract of a scientific manuscript titled '{{title}}' and with keywords '{{keywords}}': {{paragraph}}
    
    Revised abstract:
providers:
  - ollama:mistral:7b-instruct-fp16
scenarios:
  - config:
      - vars:
          test_description: original
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: 'genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits'
          paragraph: Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. Here we introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. This representation is based on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. In conclusion, by incorporating groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: spelling/grammar errors
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: 'genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits'
          paragraph: Genes act in concierto with each other in specifico contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. Here we introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. This representation is base on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantl associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. In conclusion, by incorporating, groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal, potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: does not start with background
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: 'genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits'
          paragraph: We introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. PhenoPLIER's representation is based on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. In conclusion, by incorporating groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: does not describe the method or approach proposed
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: 'genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits'
          paragraph: Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Our results in this study show that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. In conclusion, by incorporating groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: does not provide concrete results
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: 'genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits'
          paragraph: Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. Here we introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. This representation is based on modules of genes with similar expression patterns across the same conditions. In conclusion, by incorporating groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: does not provide an interpretation of the results and their implications
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: 'genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits'
          paragraph: Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. Here we introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. This representation is based on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER.
    tests:
      - description: Abstract
        assert:
          - type: python
            # Starts with capital letter
            value: |
              print(output.strip()[0].isupper())
          - type: python
            # Ends with period
            value: |
              print(output.strip()[-1] == ".")
          - type: python
            # No newlines in output
            value: |
              print("\n" not in output.strip())
          - type: python
            # No manuscript title in output
            value: |
              title = context["vars"]["title"]
              print(title not in output)
          - type: not-icontains-any
            value:
              - "authors"
          - type: python
            # Length of output is between 0.6 and 1.2 times the length of the input
            value: |
              paragraph = context["vars"]["paragraph"]
              print(
                (len(output) > 0.6 * len(paragraph)) and (len(output) < 1.2 * len(paragraph))
              )
          - type: python
            value: |
              from manubot_evals.utils import eval_rubric
              t=eval_rubric(
                output,
                context["vars"]["title"],
                "has no spelling errors, and its grammar and punctuation are correct",
              )
              print(t)
          - type: python
            value: |
              from manubot_evals.utils import eval_rubric
              t=eval_rubric(
                output,
                context["vars"]["title"],
                "the first sentences of the abstract introduce the context of the research (i.e., the broader field of research), and right after that, the context is narrowed until it lands on the research gap",
              )
              print(t)
          - type: python
            value: |
              from manubot_evals.utils import eval_rubric
              t=eval_rubric(
                output,
                context["vars"]["title"],
                "before describing any result, it describes the proposed method or approach that fills the research gap",
              )
              print(t)
          - type: python
            value: |
              from manubot_evals.utils import eval_rubric
              t=eval_rubric(
                output,
                context["vars"]["title"],
                "before mentioning any conclusion or implication, it describes concrete results obtained using the proposed method or approach",
              )
              print(t)
          - type: python
            value: |
              from manubot_evals.utils import eval_rubric
              t=eval_rubric(
                output,
                context["vars"]["title"],
                "it ends with a conclusion that interprets the results to answer the research gap, and then it highlights how that conclusion moves the broader field forward",
              )
              print(t)
