# This configuration runs each prompt through a series of example inputs and checks if they meet requirements.
# Learn more: https://promptfoo.dev/docs/configuration/guide

prompts:
  - |-
    Revise the following abstract of a scientific manuscript: {{paragraph}}
    Revised paragraph:
  - |-
    You are a professional copyeditor specialized in scholarly text. Revise the following abstract of a scientific manuscript: {{paragraph}}
    Revised paragraph:
  - |-
    Revise the following abstract of a scientific manuscript (with the title '{{title}}' and keywords '{{keywords}}'): {{paragraph}}
    Revised paragraph:
  - |-
    You are a professional copyeditor specialized in scholarly text. Revise the following abstract of a scientific manuscript (with the title '{{title}}' and keywords '{{keywords}}'): {{paragraph}}
    Revised paragraph:
providers:
  - ollama:mistral:7b-instruct-fp16
defaultTest:
  options:
    provider: ollama:llama2:7b-chat-fp16
scenarios:
  - config:
      - vars:
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: 'genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits'
          paragraph: Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. Here we introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. This representation is based on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. By incorporating groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal potential targets missed by single-gene strategies.
      - vars:
          title: An efficient not-only-linear correlation coefficient based on machine learning
          keywords: 'correlation coefficient, nonlinear relationships, gene expression'
          paragraph: Correlation coefficients are widely used to identify patterns in data that may be of particular interest. In transcriptomics, genes with correlated expression often share functions or are part of disease-relevant biological processes. Here we introduce the Clustermatch Correlation Coefficient (CCC), an efficient, easy-to-use and not-only-linear coefficient based on machine learning models. CCC reveals biologically meaningful linear and nonlinear patterns missed by standard, linear-only correlation coefficients. CCC captures general patterns in data by comparing clustering solutions while being much faster than state-of-the-art coefficients such as the Maximal Information Coefficient. When applied to human gene expression data, CCC identifies robust linear relationships while detecting nonlinear patterns associated, for example, with sex differences that are not captured by linear-only coefficients. Gene pairs highly ranked by CCC were enriched for interactions in integrated networks built from protein-protein interaction, transcription factor regulation, and chemical and genetic perturbations, suggesting that CCC could detect functional relationships that linear-only methods missed. CCC is a highly-efficient, next-generation not-only-linear correlation coefficient that can readily be applied to genome-scale data and other domains across different data types.
    tests:
      - description: Abstract tests
        assert:
          - type: python
            # Starts with capital letter
            value: |
              print(output.strip()[0].isupper())
          - type: python
            # Ends with period
            value: |
              print(output.strip()[-1] == ".")
          - type: python
            # No newlines in output
            value: |
              print("\n" not in output.strip())
          - type: python
            # No manuscript title in output
            value: |
              title = context["vars"]["title"]
              print(title not in output)
          - type: not-icontains-any
            value:
              - "authors"
          - type: python
            # Length of output is between 0.6 and 1.2 times the length of the input
            value: |
              paragraph = context["vars"]["paragraph"]
              print(
                (len(output) > 0.6 * len(paragraph)) and (len(output) < 1.2 * len(paragraph))
              )
          - type: llm-rubric
            value: has no spelling errors, and correct grammar and punctuation
          - type: llm-rubric
            value: starts with context related to the research question
          - type: llm-rubric
            value: describes what is the gap in the research field
          - type: llm-rubric
            value: describes a novel method or approach that address a gap in the research field
          - type: llm-rubric
            value: describes the results
          - type: llm-rubric
            value: ends by discussing the implications of the results
