prompts:
  - file://../../prompts/baseline.txt
  - file://../../prompts/candidate.txt

providers:
  - id: openai:gpt-4-0613
    config:
      temperature: 0
      max_tokens: 1024

# Default asserts applied to each test case below
defaultTest:
  # Make sure that output...
  assert:
    # ...starts with capital letter
    - type: python
      value: output.strip()[0].isupper()

    # ...ends with period
    - type: python
      value: output.strip()[-1] == "."

    # ...is a single paragraph
    - type: python
      value: len(output.strip().split("\n")) == 1

    # ...doesn't include manuscript title
    - type: python
      value: context["vars"]["title"] not in output

    # ...doesn't reference authors, keywords, introduction, etc
    - type: not-icontains-any
      value:
        - "authors"
        - "Introduction:"
        - "Keywords:"
        - "References:"

    # ...is roughly same length as input
    - type: python
      value: |
        input = context["vars"]["content"]
        input_words = len(input.strip().split())
        output_words = len(output.strip().split())
        response = (output_words > 0.5 * input_words) and (output_words < 2 * input_words)
        print(response)

# Make sure that output...
tests:
  # ...has no spelling errors
  - vars:
      test_description: Has no spelling errors
      title: file://./inputs/title.txt
      keywords: file://./inputs/keywords.txt
      content: file://./inputs/has_spelling_errors.md
    assert:
      - type: not-icontains-any
        value:
          - "karry"
          - "ekspression"
          - "improoved"

  # ...keeps most references to other articles and doesn't make them up
  - vars:
      test_description: Keeps most references to other articles and doesn't make them up
      title: file://./inputs/title.txt
      keywords: file://./inputs/keywords.txt
      content: file://./inputs/has_references_to_articles.md
    assert:
      - type: python
        value: |
          input = context["vars"]["content"]
          
          references = {
            "@pmid:19104045",
            "@doi:10.1038/ng.3259",
            "@doi:10.1038/s41467-018-06022-6",
            "@doi:10.1126/science.aaz1776",
            "@doi:10.1038/s41586-020-2559-3",
            "@doi:10.1038/s41576-019-0200-9",
            "@doi:10.1038/ng.3314",
            "@doi:10.1371/journal.pgen.1008489",
            "@doi:10.1038/nature11247",
            "@doi:10.1038/nature14248",
            "@doi:10.1038/nature12787",
            "@doi:10.1038/s41586-020-03145-z",
            "@doi:10.1038/s41586-020-2559-3",
            "@doi:10.1126/science.aaz1776",
            "@doi:10.1038/s41588-018-0081-4",
            "@doi:10.1016/j.ajhg.2018.04.002",
            "@doi:10.1038/s41588-018-0081-4",
            "@doi:10.1038/ncomms6890",
            "@pmid:20624743",
            "@pmid:14707169",
            "@doi:10.1073/pnas.0810772105",
          }
          
          # keep only references that are present in the input (this is needed because
          #  references might be removed from the input in some cases)
          references = [ref for ref in references if ref in input]
          
          count = len([ref for ref in references if ref in output])
          print(count / len(references) > 0.50)

      - type: python
        value: |
          import re
          
          input = context["vars"]["content"]
          
          references = {
            "@pmid:19104045",
            "@doi:10.1038/ng.3259",
            "@doi:10.1038/s41467-018-06022-6",
            "@doi:10.1126/science.aaz1776",
            "@doi:10.1038/s41586-020-2559-3",
            "@doi:10.1038/s41576-019-0200-9",
            "@doi:10.1038/ng.3314",
            "@doi:10.1371/journal.pgen.1008489",
            "@doi:10.1038/nature11247",
            "@doi:10.1038/nature14248",
            "@doi:10.1038/nature12787",
            "@doi:10.1038/s41586-020-03145-z",
            "@doi:10.1038/s41586-020-2559-3",
            "@doi:10.1126/science.aaz1776",
            "@doi:10.1038/s41588-018-0081-4",
            "@doi:10.1016/j.ajhg.2018.04.002",
            "@doi:10.1038/s41588-018-0081-4",
            "@doi:10.1038/ncomms6890",
            "@pmid:20624743",
            "@pmid:14707169",
            "@doi:10.1073/pnas.0810772105",
          }
          
          # keep only references that are present in the input (this is needed because
          #  references might be removed from the input in some cases)
          references = [ref for ref in references if ref in input]
          
          # capture current references in the output using a regex
          output_references = re.findall(r'@[^ ;\]]+', output)
          
          n_fake_refs = len([ref for ref in output_references if ref not in references])
          print(n_fake_refs == 0)

  # adheres to C-C-C by starting with context
  - vars:
      test_description: starts with context
      title: file://./inputs/title.txt
      keywords: file://./inputs/keywords.txt
      content: file://./inputs/doesnt_start_with_context.md
    assert:
      - type: python
        value: ("transcription-wide association study" in output.split(".")[0].lower())
