prompts:
  - file://../../prompts/baseline.txt
  - file://../../prompts/candidate.txt
providers:
  - ollama:mistral:7b-instruct-fp16
scenarios:
  - config:
      # - vars:
      #     test_description: original
      #     title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
      #     keywords: "genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits"
      #     paragraph: Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. Here we introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. This representation is based on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. In conclusion, by incorporating groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: spelling/grammar errors
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: "genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits"
          paragraph: Genes act in concierto with each other in specifico contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. Here we introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. This representation is base on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantl associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. In conclusion, by incorporating, groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal, potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: does not start with background
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: "genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits"
          paragraph: We introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. PhenoPLIER's representation is based on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. In conclusion, by incorporating groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: does not describe the method or approach proposed
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: "genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits"
          paragraph: Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Our results in this study show that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER. In conclusion, by incorporating groups of co-expressed genes, PhenoPLIER can contextualize genetic associations and reveal potential targets missed by single-gene strategies. PhenoPLIER provides a novel framework for interpreting genetic associations through the lens of gene modules.
      - vars:
          test_description: does not provide an interpretation of the results and their implications
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: "genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits"
          paragraph: Genes act in concert with each other in specific contexts to perform their functions. Determining how these genes influence complex traits requires a mechanistic understanding of expression regulation across different conditions. It has been shown that this insight is critical for developing new therapies. Transcriptome-wide association studies have helped uncover the role of individual genes in disease-relevant mechanisms. However, modern models of the architecture of complex traits predict that gene-gene interactions play a crucial role in disease origin and progression. Here we introduce PhenoPLIER, a computational approach that maps gene-trait associations and pharmacological perturbation data into a common latent representation for a joint analysis. This representation is based on modules of genes with similar expression patterns across the same conditions. We observe that diseases are significantly associated with gene modules expressed in relevant cell types, and our approach is accurate in predicting known drug-disease pairs and inferring mechanisms of action. Furthermore, using a CRISPR screen to analyze lipid regulation, we find that functionally important players lack associations but are prioritized in trait-associated modules by PhenoPLIER.
    tests:
      - description: Abstract
        assert:
          # Starts with capital letter
          - type: python
            value: output.strip()[0].isupper()

          # Ends with period
          - type: python
            value: output.strip()[-1] == "."

          # Single paragraph
          - type: python
            value: len(output.strip().split("\n")) == 1

          # No manuscript title
          - type: python
            value: context["vars"]["title"] not in output

          # No headings (?)
          - type: not-icontains-any
            value:
              - "Authors:"
              - "Abstract:"
              - "Keywords:"
              - "References:"

          # No spelling errors
          - type: not-icontains-any
            value:
              - "concierto"
              - "specifico"
              - "significantl "

          # Length of output roughly same as length of input
          - type: python
            value: |
              paragraph = context["vars"]["paragraph"]
              paragraph_words = len(paragraph.strip().split())
              output_words = len(output.strip().split())
              response = (output_words > 0.5 * paragraph_words) and (output_words < 1.6 * paragraph_words)
              print(response)

          # Method not mentioned at beginning
          - type: python
            value: ("PhenoPLIER" not in output.split(".")[0])

          # Method mentioned before results
          - type: python
            value: |
              methods_start = output.find("PhenoPLIER")
              results_start = max(
                  output.find("CRISPR"),
                  output.find("lipid"),
                  output.find("drug-disease"),
              )
              response = methods_start < results_start
              print(response)

          # CRISPR mentioned
          - type: contains
            value: "CRISPR"

          # Conclusions included
          - type: python
            value: |
              keywords = [
                "overall",
                "conclusion",
                "insight",
                "novel",
                "potential",
                "broader",
                "ultimately",
                "advancement",
                "valuable",
                "our study",
                "this study",
                "our work",
                "this work",
                "our approach",
                "research",
                "critical gap",
                "understanding",
                "powerful",
                "advancing",
                "importance",
                "findings",
                "highlight",
                "uncovering",
              ]
              # try to capture the first paragraph (because sometimes models add
              # explanations below the revised paragraph)
              first_paragraph = output.strip().split("\n")[0]
              last_sentences = ".".join(first_paragraph.strip().split(".")[-2:]).lower()
              response = any(s in last_sentences for s in keywords)
              print(response)
